### ISSUE TITLE
build VPN Pritunl - Docker

### ISSUE THREAD

**Issue by tnubeo1111** [tnubeo1111/Linux#12]
Mục đích là tạo một VPN có thể kết nối ra ngoài internet được.

Chuẩn bị:
            - Subdomain: vpn.thanhtha.name.vn trỏ về IP server: 61.14.234.55 (Nên thay thành của bạn nhé)
            - Máy chủ phải có docker.

**Tìm hiểu về Pritunl:**
    
     Pritunl là một phần mềm mã nguồn mở cung cấp dịch vụ VPN. Pritunl có thể được cài đặt trên nhiều nền tảng khác nhau, bao gồm Linux, Windows, macOS, và Docker.

     Pritunl cung cấp nhiều tính năng bảo mật và quản lý, bao gồm:

      - Xác thực mạnh: Pritunl hỗ trợ nhiều phương thức xác thực mạnh, bao gồm username/password, certificate, và two-factor authentication.
      - Quản lý người dùng: Pritunl cung cấp một giao diện web để quản lý người dùng, bao gồm tạo, chỉnh sửa, và xóa người dùng.
      - Quản lý kết nối: Pritunl cung cấp một giao diện web để quản lý kết nối VPN, bao gồm tạo, chỉnh sửa, và xóa kết nối.
      - Quản lý nhật ký: Pritunl lưu trữ nhật ký hoạt động của VPN, giúp bạn theo dõi và phân tích hoạt động của VPN.
      - Pritunl có hai phiên bản: miễn phí và trả phí. Phiên bản miễn phí cung cấp đầy đủ các tính năng bảo mật và quản lý. Phiên bản trả phí cung cấp thêm một số tính năng nâng cao, chẳng hạn như khả năng quản lý nhiều máy chủ VPN.

    Để sử dụng Pritunl, bạn cần tạo một tài khoản Pritunl. Sau đó, bạn có thể cài đặt Pritunl trên máy chủ của mình. Khi Pritunl đã được cài đặt, bạn có thể tạo kết nối VPN và mời người dùng khác tham gia vào kết nối VPN.

Dưới đây là một số lợi ích của việc sử dụng Pritunl:

    Dễ sử dụng: Pritunl có giao diện web đơn giản và dễ sử dụng.

       -  Miễn phí: Phiên bản miễn phí của Pritunl cung cấp đầy đủ các tính năng bảo mật và quản lý.
       -  Mở rộng: Pritunl có thể được cài đặt trên nhiều nền tảng khác nhau.
       -  Tính bảo mật cao: Pritunl cung cấp nhiều tính năng bảo mật mạnh mẽ.

Các bước cài đặt VPN Pritunl bằng docker

  Bước 1 Tải docker nếu chưa có docker nhé.
  
```
  sudo apt update 
  sudo apt install docker.io -y
  sudo apt install docker-compose -y
```

  Bước 2 Tạo thư mục lưu file docker-compose.yml
  
 ```
  mkdir docker-vpn
  cd docker-vpn
  touch  docker-compose.yml
```

  Trong file docker-compose.yml các bạn dán nội dung sau:

```
  version: '3'

services:
  pritunl:
    image: 'jippi/pritunl:latest'
    privileged: true
    ports:
      - '80:80'
      - '443:443'
      - '1194:1194/udp'  
      - '1194:1194/tcp'
     
#    (các bạn nên thay port khác để chạy nhé để có thể bảo mật tốt hơn ví dụ như 2000:1194 ở đây 2000 là port mà chúng ta sẽ # #    chạy host ở ngoài còn port 1194 là port của container)

    volumes:
      - './pritunl_data:/var/lib/pritunl'
      - './pritunl_db:/var/lib/mongodb'
     
# Đây là 2 thư mục chúng ta sẽ mount dữ liệu từ bên trong container ra bên ngoài để trường hợp khi chúng ta đỡ xóa docker # # images đi và tải lại thì dữ liệu vẫn còn nguyên vọng nhé ở đây ở máy chủ là 2 thư mục './pritunl_data và ./pritunl_db còn thư # # mục container là /var/lib/pritunl và /var/lib/mongodb. Có nghĩa là khi container chạy thì 2 thư mục của container sẽ được # # 
# mount vào 2 thư mục của máy host bên ngoài

volumes:
  pritunl_data:
    driver: local
  pritunl_db:
    driver: local
```

Sau khi chạy xong docker mọi người có thể lên trình duyệt gõ https://IP_server nó sẽ xuất hiện trang login

Để có tài khoản mọi người chạy lên sau:

`docker exec -it [container_name] pritunl default-password`

Bước 3 Sau khi vào được admin mọi người nhớ tạo tài khoản, password và sudomain nha (https://prnt.sc/uHFzjopu0s70)

Lưu ý: khi tạo server mọi người nhớ để ý cái port nhé nên tạo server với port khớp với port chúng ta đang chạy trên docker compose nhé (https://prnt.sc/l7ghs20QZf-C)

Như thê là xong rồi.
