### ISSUE TITLE
build NextCloud on server | v2 docker

### ISSUE THREAD

**Issue by tnubeo1111** [tnubeo1111/Linux#21]
-- Các bước build NextCloud bằng docker

```
mkdir nextcloud 

cd nextcloud

     touch docker-compose.yml

     mkdir  proxy
```

```
cd proxy (thư mục chúng ta vừa trạo trong thư mục chính nextcloud)

touch Dockerfile

touch uploadsize.conf
```

Tại thư mục proxy chúng ta thêm các đoạn code sau cho từng file

```
--Dockerfile

FROM nginxproxy/nginx-proxy:alpine

COPY uploadsize.conf /etc/nginx/conf.d/uploadsize.conf
```

```
-- uploadsize.conf

client_max_body_size 10G;

proxy_request_buffering off;
```

Tiếp theo chúng ta ra thư mục chính nextcloud để chèn code cho file docker-compose.yml

```
version: '3'

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /data/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=121212
      - MYSQL_PASSWORD=121212
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - /data/nextcloud/root_dir:/var/www/html
      - /data/nextcloud/data:/var/www/html/data
    environment:
      - VIRTUAL_HOST=file.thanhtha.name.vn                  # Thay domain thành domain của mọi người
      - LETSENCRYPT_HOST=file.thanhtha.name.vn         # Thay domain thành domain của mọi người
      - MYSQL_PASSWORD=121212
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    depends_on:
      - db

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /data/nextcloud/certs:/etc/nginx/certs
      - /data/nextcloud/vhost.d:/etc/nginx/vhost.d
      - /data/nextcloud/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock
      - /data/nextcloud/nginx/conf.d:/etc/nginx/conf.d

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - /data/nextcloud/certs:/etc/nginx/certs
      - /data/nextcloud/acme:/etc/acme.sh
      - /data/nextcloud/vhost.d:/etc/nginx/vhost.d:rw
      - /data/nextcloud/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - proxy
```

Sau khi chèn đoạn code cho file docker-compose.yml

Bước tiếp theo chúng ta sẽ tạo các thư mục tương đương với các thư mục trong file docker-compose.yml để khi chạy docker các file trong container có thể mount về các thư mục đó. Để thuận tiện cho sau này chúng ta có thể dễ dàng sữa file thì container vẫn nhận hoặc backup lại.

```
mkdir -p /data/nextcloud

mkdir /data/nextcloud/db

mkdir /data/nextcloud/root_dir

mkdir /data/nextcloud/data

mkdir /data/nextcloud/certs

mkdir /data/nextcloud/vhost.d

mkdir /data/nextcloud/html

mkdir /data/nextcloud/nginx/conf.d

mkdir /data/nextcloud/acme
```
--> Như thế là xong các bước để stup cho NextCloud bằng docker

-- Các bước setup cho collabora  bằng docker

```
mkdir collabora 

cd collabora

touch docker-compose.yml
```

Sau đó chúng ta chèn code vào docker-compose.yml

```
version: "3"
services:
  collabora:
    container_name: collabora
    image: collabora/code:latest
    cap_add:
        - MKNOD
    environment:
      - domain=collabora.thanhtha.name.vn     # vui lòng thay subdomain khác nhá.
      - username=admin
      - password=12121212
      - extra_params=--o:ssl.enable=false
    ports:
      - 9980:9980
    restart: always
    volumes:
      - /etc/localtime:/etc/localtimer
```

Như thế là xong việc setup collabora bằng docker
